"""add language to posts

Revision ID: 658a4aa25cb4
Revises: f4a761fff5b0
Create Date: 2018-10-31 17:40:42.162580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658a4aa25cb4'
down_revision = 'f4a761fff5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
